language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install darcs libgtksourceview-3.0-dev
  - cabal install Cabal
  - cabal install gtk2hs-buildtools
install:
  - cabal install cabal-meta cabal-src
script:
  - cabal-meta install --enable-tests --force-reinstalls
notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
